version: 0.2

phases:
   pre_build:
    commands:
      - npm install
      
   build:
    commands:  
      - npm i --save-dev @react-native-community/cli
      - chmod +x gradlew
      #- ./gradlew assembleDebug
      - ./gradlew assembleRelease
      - ./gradlew :app:bundleRelease
      
artifacts:
  files:
      - '**/*.aab'
  discard-paths: 'yes'
