version: 0.2

phases:
   pre_build:
    commands:
      - npm install
      
   build:
    commands:  
      - npm i --save-dev @react-native-community/cli
      - chmod +x gradlew
      - ./gradlew assembleDebug
      
artifacts:
  files:
      - '**/*.apk'
  discard-paths: 'yes'